default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: root
  password: root@123
development:
  <<: *default
  database: web_kart_development
test:
  <<: *default
  database: web_kart_test
production:
  <<: *default
  database: web_kart_production