default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres
development:
  <<: *default
  database: web_kart_development
test:
  <<: *default
  database: web_kart_test
production:
  <<: *default
  database: web_kart_production